# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger: none
stages: 
- stage: 'Build_Web_App'
  jobs:
    - job: Build
      pool:
        vmImage: 'windows-latest'

      variables:
        solution: '**/*.sln'
        buildPlatform: 'Any CPU'
        buildConfiguration: 'Release'

      steps:
      - task: NuGetToolInstaller@1
        displayName: 'NuGetToolInstaller...'
      - task: NuGetCommand@2
        displayName: 'Nuget - restore solution files'
        inputs:
          restoreSolution: '$(solution)'

      - task: VSBuild@1
        displayName: 'Building application...'
        inputs:
          solution: '$(solution)'
          msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
          platform: '$(buildPlatform)'
          configuration: '$(buildConfiguration)'

        #publish pipeline artifact to Az pipeline 
      - task: PublishPipelineArtifact@1
        name: 'PublishPipelineArtifact'
        displayName: 'Publish pipeline artifact'
        inputs:
          targetPath: '$(Build.ArtifactStagingDirectory)'
          artifact: 'CI'
          publishLocation: 'pipeline'

- stage: 'Deploy_To_Dev'
  dependsOn: "Build_Web_App"
  jobs: 
    - job: DeployDev
      pool:
        vmImage: 'windows-latest'
      
      steps:
        #download pipeline artifacts
        - task: DownloadPipelineArtifact@2
          name: 'DownloadPipeLineArtifact'
          displayName: 'Download pipeline artifact'
          inputs:
            buildType: 'current'
            artifactName: 'CI'
            targetPath: '$(Pipeline.Workspace)'
        
        #deploy to azure app service
        - task: AzureRmWebAppDeployment@5
          displayName: 'Deploying application...'
          inputs:
            ConnectionType: 'AzureRM'
            azureSubscription: 'Azure subscription 1(4c0ad907-15a8-43c8-8818-a28d35e340c3)'
            appType: 'webApp'
            WebAppName: 'vkproducts'
            packageForLinux: '$(Pipeline.Workspace)/**/*.zip'
  